### ISSUE TITLE
Cron

### ISSUE THREAD

**Issue by kubasimon** [cedvan/docker-toran-proxy#1]
Hi, do you plan to add cron entry for running 'php bin/cron' which download files for proxy on background?

**Comment by cedvan** [comment]
Hi,

Yes I work on it currently, wait a moment please :)

**Comment by cedvan** [comment]
Ok, cron work every minute !

Use version [**1.1.6-2**](https://github.com/cedvan/docker-toran-proxy/releases/tag/1.1.6-2)
`docker pull cedvan/toran-proxy:1.1.6-2`

**Comment by kubasimon** [comment]
Thx, cron is running, will post issues/pulls for other problems:)
