### ISSUE TITLE
localhost being used instead of env TORAN_HOST

### ISSUE THREAD

**Issue by ssx** [cedvan/docker-toran-proxy#17]
Hi,

On deploying this image with TORAN_HOST set, it seems that the internal package URLs are being presented as localhost instead of the value in TORAN_HOST. 

The initial HTTP page for toran shows the correct host, but it looks like the JSON being dispatched by toran still think its serving as localhost.

Example:
- Installing aws/aws-sdk-php (2.8.22)
  Downloading: 0%  
  Failed, trying the next URL (404: The "http://localhost/repo/packagist/dists/aws/aws-sdk-php/2.8.22.0/d24eb9c69e5b6bdab53a7e223e58507bbea842dd.zip" file could not be downloaded (HTTP/1.1 404 Not Found))

TORAN_CRON_TIMER    fifteen
TORAN_HOST  xxxxxxxxx.node.tutum.io
TORAN_PHP_TIMEZONE  Europe/London
TORAN_TOKEN_GITHUB  xxxxxxxxx

Any ideas?

**Comment by cedvan** [comment]
Hi @ssx, 

It's strange, I'll get them as possible reasons.
I will come to you when I have news ;)

**Comment by ssx** [comment]
Thanks! :) I should have a little time to look at it this evening too, so I'll post back if I find anything

**Comment by ssx** [comment]
Hi!

I think this may be something to do with the git clone url being unset, what do you have this configured as? bearing in mind SSHd isn't running on the machine I'm assuming this is a HTTP URL?

**Comment by cedvan** [comment]
Hi, 

Send me command use to launch toran proxy container please. 
HTTP is used by Toran Porxy for download and send package. SSHd should not be necessary.

**Comment by cedvan** [comment]
Sorry for the delay, I had little time for me :-/ !

You use a http authentification ?

**Comment by cedvan** [comment]
@ssx I wish I could help you ;)

**Comment by cedvan** [comment]
@ssx ?

**Comment by ssx** [comment]
Hi @cedvan, wasn't able to reproduce this in 1.1.7-1 so I think it's resolved itself.

**Comment by ssx** [comment]
@cedvan: looks like this one didn't go away, got this error when running a composer update:

  Failed, trying the next URL (0: The "://localhost/repo/packagist/dists/phpunit/php-token-stream/1.4.8.0/3144ae21711fb6cac0b1ab4cbe63b75ce3d4e8da.zip" file could not be downloaded: failed to open stream: No such file or directory)
    Downloading: 100%  

that's running it with:

docker run --name toran-proxy -d -p 8080:80 cedvan/toran-proxy:1.1.7-1

**Comment by cedvan** [comment]
hi @ssx,

I suppose than your `composer.lock` is corrupt by old toran-proxy version.
Remove your `composer.lock`, and launch again `composer install` to create a new `composer.lock`.

Next test a `composer update`, and give me a feedback

**Comment by ssx** [comment]
I'll give that a test now.

**Comment by cedvan** [comment]
So ?

**Comment by joshuataylor** [comment]
When accessing `http://xxx.xxx/repo/private/packages.json`, I receive the following:

```

{
    "providers": [],
    "mirrors": [
        {
            "dist-url": "://localhost/repo/private/dists/%package%/%version%/%reference%.%type%",
            "preferred": true
        }
    ],
    "providers-url": "/repo/private/p/%package%.json"
}
```

dist-url seems to have localhost.

**Comment by kop** [comment]
Hi @cedvan, I'm having exactly the same issue.

Here is my config (it's for Kubernetes):

```
containers:
        - name: toran-proxy
          image: cedvan/toran-proxy
          ports:
            - name: http
              containerPort: 80
          env:
            - name: TORAN_HOST
              value: toran-proxy.tools.domain.com
            - name: TORAN_PHP_TIMEZONE
              value: Europe/London
            - name: TORAN_TOKEN_GITHUB
              value: <TOKEN CODE HERE>
```

And in my `composer.json` I have:

```
  "repositories": [
    {"type": "composer", "url": "http://toran-proxy.tools.domain.com/repo/packagist/"},
    {"packagist": false}
  ],
```

I've deleted `composer.lock` from my project, created a new container from the scratch (no volumes were attached) and executed `composer update`. Resulting `composer.lock` still has references to `localhost`.

Now the funny part that makes me believe that it may be the issue of Toran Proxy itself.
In the UI, I see that all my dependencies are cached, however resulting `composer.lock` has references of three types: with `localhost` url, with `toran-proxy.tools.domain.com` url and with no proxy URL at all.

**Comment by cedvan** [comment]
Hi @kop, I will analyze ;)

**Comment by kop** [comment]
I was able to resolve the issue. It's not related to this image and is composer-related.
Just delete both `composer.lock` and `vendor/` folder and run `composer update`. After that everything works like a charm.

**Comment by cedvan** [comment]
Very good :) 

Thank you !

**Comment by tkarlinski** [comment]
Hi @cedvan 
I have a similar problem. But i think that is problem with no default port.
I user

**Comment by tkarlinski** [comment]
Hi @cedvan
I have a similar problem. But i think that is problem with no default port.
I use:
docker run --name toran-proxy -d \
    -p 8081:80 \
    -p 443:443 \
    -v /var/docker/.ssh/:/data/toran-proxy/ssh \
    -e "TORAN_CRON_TIMER=minutes" \
    -e "TORAN_HOST=toranproxy.dev.pl" \
    cedvan/toran-proxy:1.5.4 

  - Installing symfony/polyfill-mbstring (v1.5.0): Downloading (failed)       
 Failed, trying the next URL (404: The "http://toranproxy.dev.pl/repo/packagist/dists/symfony/polyfill-mbstring/1.5.0.0/7c8fae0ac1d216eb54349e6a8baa57d515fe8803.zip" file could not be downloaded (HTTP/1.1 404 Not Found))Downloading (100%)

Composer should be try download by **toranproxy.dev.pl:8081** but It trying download by **toranproxy.dev.pl**

**Comment by cedvan** [comment]
Hi @tkarlinski, 

Your problem is different, can you open new issue please ?

**Comment by tkarlinski** [comment]
Ok, I opened new issue here: https://github.com/cedvan/docker-toran-proxy/issues/58
