### ISSUE TITLE
This repository was not initialized, you should make sure you are running bin/cron regularly

### ISSUE THREAD

**Issue by joshuataylor** [cedvan/docker-toran-proxy#18]
This happens before running cron, would be nice if docker-toran-proxy ran cron on first boot or something?

Current Workaround: set cron to minute.

**Comment by cedvan** [comment]
Hi @joshuataylor,

This was implemented, but the synchronisation timing was delaying the start of the toran-proxy I looking for a solution ;)

**Comment by cedvan** [comment]
I currently implements supervisord to finely control the starting of the container

**Comment by cedvan** [comment]
Hi @joshuataylor,

Issue is resolved by #21 

See you
