### ISSUE TITLE
Redirect logs to stdout

### ISSUE THREAD

**Issue by kop** [cedvan/docker-toran-proxy#19]
Hi,

I was checking my Toran Proxy setup recently and noticed that `/var/log/toran-proxy/cron/cron.log` grows very fast. Container running just 15 days and it's ~200M already.

So the question is why to store this log file in the container? Maybe it's better to redirect cron output to `stdout`?

The same question applies to Nginx. It's much more convenient to have all logs redirected to Docker instead of storing them in the container.

**Comment by cedvan** [comment]
Hi,

I completely agree ! 
I'll fix as soon as possible, else you can create a pull request ;)

See you

**Comment by cedvan** [comment]
Hi @kop,

Issue is resolved by #21 

See you
