### ISSUE TITLE
v1.3 released!

### ISSUE THREAD

**Issue by adamlc** [cedvan/docker-toran-proxy#20]
v1.3 has been released with quite a few fixes! Would be great to get this supported :)

**Comment by cedvan** [comment]
hi @adamlc,

I'm working to support v1.3 ;)

Thank you !

**Comment by adamlc** [comment]
Awesome! Looking forward to it :smile:

**Comment by cedvan** [comment]
I will increase versions one by one :wink: :
- 1.2.0
- 1.3.0
- 1.3.1
- 1.3.2

**Comment by cedvan** [comment]
https://github.com/cedvan/docker-toran-proxy/pull/22 merged, v1.2.0 published !

**Comment by cedvan** [comment]
v1.3.0 and v1.3.1 have bugs, so update directly to v1.3.2, cf https://github.com/cedvan/docker-toran-proxy/pull/26

**Comment by cedvan** [comment]
Hi, 

Sorry for delay :/, lot of work... I'll upgrade to v1.3 and v1.4 quickly

**Comment by jeremyzahner** [comment]
@cedvan See #28 for a tested upgrade to 1.4.2.
