### ISSUE TITLE
SSH-Agent not running

### ISSUE THREAD

**Issue by jeremyzahner** [cedvan/docker-toran-proxy#29]
Hi there!

As far as i can see, you are not really adding the custom ssh keys to the ssh agent or even starting the ssh agent properly. Could you just quickly point me into the right direction? I can see that you are symlinking ssh keys, but not where you load them exactly.

Best,

Jeremy

**Comment by cedvan** [comment]
Hi @jeremyzahner,

Toran proxy cron need ssh keys to clone privates repositories. Cron is run by `www-data` user (https://github.com/cedvan/docker-toran-proxy/blob/master/bin/toran-proxy-cron#L10). `www-data` home directory is `/var/www`. So I add ssh keys to `/var/www/.ssh/` (https://github.com/cedvan/docker-toran-proxy/blob/master/scripts/install/ssh.sh#L13).

**Comment by jeremyzahner** [comment]
All well. I got it working.
