### ISSUE TITLE
Private repos ssh

### ISSUE THREAD

**Issue by kubasimon** [cedvan/docker-toran-proxy#3]
We are using private repos in Stash and configured in toran(satis) as 'ssh://git@stash.sowhere.com:7999/grp/repo.git'

When i check cron job - php bin/cron
i see error:

Failed to execute git clone --mirror 'ssh://git@stash.sowhere.com:7999/grp/repo.git '/var/www/app/toran/composer/cache/vcs/ssh---git-stash-grp-repogit'
  Cloning into bare repository '/var/www/app/toran/composer/cache/vcs/ssh---git-stash-grp-repogit'...
  error: cannot run ssh: No such file or directory
  fatal: unable to fork

First issue is that container is missing ssh command and second issue will emerge after that - missing ssh private key enabled in stash:
Found similar issue how to add id_rsa (http://stackoverflow.com/questions/18136389/using-ssh-keys-inside-docker-container) but I'm not sure how to solve missing ssh? Can you point me somewhere?

**Comment by cedvan** [comment]
Hum, ssh is absent. 
I'll have to fix it by updating the from ubuntu image. 
One moment please

**Comment by cedvan** [comment]
SSH is now installed to **latest**. 
You can test with this version ?

**Comment by kubasimon** [comment]
Thanks, works like a charm!
But I still have to provide ssh key to container somehow, not sure whats best practise for docker. 
(
http://stackoverflow.com/questions/18136389/using-ssh-keys-inside-docker-container advices 
RUN  echo "    IdentityFile ~/.ssh/id_rsa" >> /etc/ssh/ssh_config
or 
ADD id_rsa /root/.ssh/id_rsa
)

And when i ran cron manually, I had to confirm certificate:

The authenticity of host '[**]:7999 ([**]:7999)' can't be established.
RSA key fingerprint is bc:**:**:**:**:**:**:**:**:
Are you sure you want to continue connecting (yes/no)? y
Please type 'yes' or 'no': yes

So some way to skip this step would be nice:)

**Comment by cedvan** [comment]
- **SSH Keys :** I'm going to create a system to add ssh keys to container
- **Known hosts, I analyze different solutions :**
  - Add a configuration `KNOWN_HOST` to automatically add hosts validated to the `known_host` file of the container
  - Add `StrictHostKeyChecking no` to ssh config

One moment please

**Comment by cedvan** [comment]
I have created an option to add a **ssh configuration**.
You can test by adding ssh keys `ìd_rsa`, `ìd_rsa.pub` and `known_hosts` file to the folder ssh ?

**Comment by kubasimon** [comment]
Thanks, it works (i still have some issue creating known_hosts correcly, but i ll figure it out).

If I would start from scratch, is correct approach to create /opt/toran-proxy dirs with /opt/toran-proxy/ssh where I copy all there files?

**Comment by cedvan** [comment]
At the first launch, you can create a directory for save data `/opt/toran-proxy`.
In this directory you can add directories to your need :
- a folder **certs** with files `toran-proxy.crt` and `toran-proxy.key` for configure SSL. Need option `TORAN_HTTPS` to `true` for enabled.
- a folder **ssh** with the file `id_rsa`, `id_rsa.pub` and `known_hosts` for add permissions to user root to private repository

Now start your container toran-proxy with command :

``` sh
docker run --name toran-proxy -d \
    -v /opt/toran-proxy:/data/toran-proxy \
    cedvan/toran-proxy:latest
```

**Comment by cedvan** [comment]
It's good for you ?

**Comment by kubasimon** [comment]
yes, thank you!
