### ISSUE TITLE
How to set up private repo using ssh

### ISSUE THREAD

**Issue by csimplestring** [cedvan/docker-toran-proxy#40]
Can anybody explain about how to set up private repo? Now I want to set up my private repo from bitbucket by using git@bitbucket.org:xxx/aaa.git, but it always gives error: 

Host key verification failed. fatal: Could not read from remote repository. Please make sure you have the correct access rights and the repository exists.

I already add ssh public key id_rsa and id_rsa.pub into the ssh folder.

Thanks!

**Comment by cedvan** [comment]
hi @csimplestring,

Which version of `docker-toran-proxy` you run ?

**Comment by csimplestring** [comment]
hi @cedvan ,
I am using the 1.2.0 image, since the latest one has errors when staring the proxy.

**Comment by csimplestring** [comment]
@cedvan 
I think I found a bug in scripts/install/ssh.sh:

```
    if [ -e "$DATA_DIRECTORY/ssh/id_rsa" ]; then
        chgrp 545 $DATA_DIRECTORY/ssh/id_rsa
        chmod 600 $DATA_DIRECTORY/ssh/id_rsa
        ln -s $DATA_DIRECTORY/ssh/id_rsa /var/www/.ssh/id_rsa
    fi
```

The permission of id_rsa should be 644, not 600.

Can you verify it?

**Comment by cedvan** [comment]
Hum, I'll verify ;)

**Comment by cedvan** [comment]
@csimplestring,

600 should be good, you still have the problem with the latest version ?

**Comment by cedvan** [comment]
No reply from you so I close this issue . If you need help again, reopen :wink:
