### ISSUE TITLE
Ability to add HTTP Basic Auth Credentials

### ISSUE THREAD

**Issue by adamgoose** [cedvan/docker-toran-proxy#47]
It'd be really nice if I could optionally provide TORAN_HTTP_USERNAME and TORAN_HTTP_PASSWORD environment variables to configure HTTP basic auth automatically.

It appears as there's no way to configure HTTP Basic Auth.

**Comment by cedvan** [comment]
Hi @adamgoose,

It should be possible, I try to implement this weekend :wink:

**Comment by adamgoose** [comment]
Not if I beat you to it! ;) Working on a fork right now.

**Comment by cedvan** [comment]
Thank you for contributing :smiley: .

Please use : 
- `TORAN_AUTH_ENABLE` (`true`/`false` - default `false`)
- `TORAN_AUTH_USER`
- `TORAN_AUTH_PASSWORD`

**Comment by adamgoose** [comment]
See #48

**Comment by cedvan** [comment]
Nice, I've commented :wink:

**Comment by adamgoose** [comment]
No comments on my end yet. Might have to "submit the review"

**Comment by cedvan** [comment]
[Build](https://hub.docker.com/r/cedvan/toran-proxy/builds/bzdaorpplcqrwirvh8zyvaa/) finished, this issue is ok for you ?

**Comment by adamgoose** [comment]
Yes, thank you! :) It'd be nice if we could tag this as like `1.5.3-1` or something.

**Comment by cedvan** [comment]
Yes, it's planned, just wait some days :wink:

**Comment by adamgoose** [comment]
Haha alrighty. I'll work with `latest` for now. Thanks so much for your prompt feedback on this! :)

**Comment by cedvan** [comment]
Hi @adamgoose,

New release [1.5.3-1](https://github.com/cedvan/docker-toran-proxy/releases/tag/1.5.3-1) was created
