### ISSUE TITLE
Rebuild the Docker Repo?

### ISSUE THREAD

**Issue by etcook** [cedvan/docker-toran-proxy#5]
It doesn't seem like the docker registry image has been rebuilt with the latest master changes.

**Comment by cedvan** [comment]
New building launched

**Comment by cedvan** [comment]
Ok, latest version is up to date
https://registry.hub.docker.com/u/cedvan/toran-proxy/builds_history/148062/

**Comment by etcook** [comment]
Thanks for this. Could you create an autobuild or this or setup the webhooks to automate it? Thanks!

**Comment by cedvan** [comment]
It is already like that. Each time a change has autobuild is launched on the docker hub registry for the tags master/latest

**Comment by cedvan** [comment]
I close, if you need re-open please
