### ISSUE TITLE
nginx listen on specific host

### ISSUE THREAD

**Issue by ceesvanegmond** [cedvan/docker-toran-proxy#50]
Using this wonderful package, in the vhost of nginx, the servername _ is used.
https://github.com/cedvan/docker-toran-proxy/blob/master/assets/vhosts/toran-proxy-http.conf#L3

Wouldn't it be good to add the TORAN_HOST variable there instead of _?

**Comment by cedvan** [comment]
Hi @ceesvanegmond,

Toran proxy is the only http service running in the container, so defined more precisely the destination host is useless in this context.

**Comment by ceesvanegmond** [comment]
@cedvan True, but if you have more containers on one host on other ports, this toran proxy wil listen on all hosts. I think i'ts an good idea to let toranproxy listen on specific host.

**Comment by cedvan** [comment]
I don't understand, containers are isolated with specific ip, they may not come into conflict. Or maybe you start toran-proxy container with `--net=host` !?

**Comment by haphan** [comment]
@ceesvanegmond Let toranproxy listen on specific host does not solve the real issue is that your toran container is listening to port 80/443. Which means you cannot have another container running on those ports.

I solved this issue by running jwilder/nginx-proxy

```bash
docker run -d \
    --name proxy \
    --restart=always \
    -p 80:80 -p 443:443 \
    -v /var/run/docker.sock:/tmp/docker.sock:ro \
    -v /root/cert:/etc/nginx/certs:ro \
    jwilder/nginx-proxy

docker run --name toran-proxy --restart=always -d \
    -e VIRTUAL_HOST=toranproxy.example.com \
    -e HTTPS_METHOD=noredirect \
    -e TORAN_CRON_TIMER=half \
    -e TORAN_REVERSE=true \
    -e TORAN_HOST=toranproxy.example.com \  #mainly for toran to generate correct URL
    -e TORAN_TOKEN_GITHUB=your_github_token_jhere \arrrr
    -e 'PHP_TIMEZONE=Asia/Singapore' \
    -v /opt/toran-proxy:/data/toran-proxy \
    cedvan/toran-proxy:latest
```

**Comment by jeremyzahner** [comment]
@haphan @cedvan @ceesvanegmond I think messing with the hosts network directly is not something we should do inside this image. If you need such functionality (for example if you want to expose multiple webservers on the same host), you should use a proxy.

Edit: This is a good read https://docs.docker.com/engine/userguide/networking/

**Comment by cedvan** [comment]
I agree with jeremyzahner and @haphan.

I close this issue ;)
