### ISSUE TITLE
[Info] Toran behind Internet proxy

### ISSUE THREAD

**Issue by rogeriolino** [cedvan/docker-toran-proxy#52]
Hi,

I work on company that use proxy for Internet control. So I need to configure the variables `http_proxy`/`https_proxy` in all servers with Internet access requirement.

The problem (my problem) with this image is the following command:

    sudo -u www-data bash -c "cd /var/www && php bin/cron -v"

The command above clear the proxy vars. So, I need to change to:

    sudo -E -u www-data bash -c "cd /var/www && php bin/cron -v"

Regards.

**Comment by cedvan** [comment]
Hi @rogeriolino,

I'll test and create PR to add `-E` ;)

**Comment by cedvan** [comment]
See https://github.com/cedvan/docker-toran-proxy/pull/54

**Comment by cedvan** [comment]
Done
