### ISSUE TITLE
[Feature request] PHP7 support

### ISSUE THREAD

**Issue by haphan** [cedvan/docker-toran-proxy#53]
@cedvan Any plan to upgrade docker image to use the new `PHP 7`?  (not really new but well current image is using `PHP 5.5`)

Another enhancement would be switching to `alpine` linux perhaps?

**Comment by jeremyzahner** [comment]
@cedvan Toran does support PHP7. So i don't see why not. The alpine request is a different thing.

**Comment by cedvan** [comment]
hi,

Why not, I'll test to build new image with alpine ;)

**Comment by bauer01** [comment]
Hi!
any progress with alpine version?

**Comment by cedvan** [comment]
hi @bauer01,

new issue for that : https://github.com/cedvan/docker-toran-proxy/issues/60
