### ISSUE TITLE
Upgrade to v1.5.4

### ISSUE THREAD

**Issue by EAnushan** [cedvan/docker-toran-proxy#56]
Can you tag a new image that uses toran proxy version 1.5.4 please?

There is a bug fix in this patch release as noted at https://github.com/composer/composer/issues/6383#issuecomment-320595326

**Comment by cedvan** [comment]
Hi @EAnushan,

I'll create a PR ;)

**Comment by cedvan** [comment]
@EAnushan,

Done, cf. https://github.com/cedvan/docker-toran-proxy/releases/tag/1.5.4
