### ISSUE TITLE
compoer/toran omits port ?

### ISSUE THREAD

**Issue by tkarlinski** [cedvan/docker-toran-proxy#58]
Hi

I have problem with no default port.

I use:
docker run --name toran-proxy -d 
**-p 8081:80** 
-p 443:443 
-v /var/docker/.ssh/:/data/toran-proxy/ssh 
-e "TORAN_CRON_TIMER=minutes" 
-e "TORAN_HOST=toranproxy.dev.pl" 
cedvan/toran-proxy:1.5.4

composer.json:
    "repositories": [
        {"type": "composer", "url": "http://**toranproxy.dev.pl:8081**/repo/packagist/"},
        {"packagist": false}
    ],

After "composer install":
...
Installing symfony/polyfill-mbstring (v1.5.0): Downloading (failed)
Failed, trying the next URL (404: The "http://toranproxy.dev.pl/repo/packagist/dists/symfony/polyfill-mbstring/1.5.0.0/7c8fae0ac1d216eb54349e6a8baa57d515fe8803.zip" file could not be downloaded (HTTP/1.1 404 Not Found))Downloading (100%)

Composer should be try download by **toranproxy.dev.pl:8081** but It trying download by **toranproxy.dev.pl**

**Comment by cedvan** [comment]
Hi @tkarlinski,

Add in your command the environment variable `TORAN_HTTP_PORT=8081`

cf. https://github.com/cedvan/docker-toran-proxy#toran-proxy-options

**Comment by tkarlinski** [comment]
@cedvan Thank you very much
